JSMpeg options + key event defaults prevented
crybapp/web pull request #43
Opened 2019-10-19 06:41 UTC by lnneth

2019-10-19 06:49 UTC, JeDaYoshi commented
Should make the bitrate to match and will also now catch more keys.

2019-10-19 19:21 UTC, Simonx22 commented
This currently breaks input. Commenting out ``event.preventDefault()`` for the mouse inputs seems to fix it apparently.

2019-10-19 19:36 UTC, Simonx22 commented
Remove these two lines and the keys will work. Other than that: LGTM! Pressing CTRL no longer breaks the input inside the VM.

2019-10-19 19:36 UTC, Simonx22 requested changes

2019-10-19 19:36 UTC, Simonx22 commented on components/player/viewer.vue
> +		event.preventDefault()
Remove this line

2019-10-19 19:36 UTC, Simonx22 commented on components/player/viewer.vue
> +		event.preventDefault()
And this one

2019-10-22 05:35 UTC, Simonx22 commented
Current state of this PR:
- it fixes the keys being stuck bug
- scrolling on Firefox is broken but it's not related to this PR

2019-11-02 23:20 UTC, JeDaYoshi commented
I will merge this for now and make an issue for the scrolling bug. At least this is a fix that will help some, and I'd like this being there for now. Thanks @lnneth for the fix!

2019-11-02 23:20 UTC, merged